"""
In-memory report store for prototype.
Will be replaced by Firebase in production.
"""

import uuid
from datetime import datetime, timedelta, timezone


def next_id() -> str:
    return str(uuid.uuid4())[:8]


# ── Seed data ────────────────────────────────────────────────────────────────
# A handful of reports spread across Malaysia so the map isn't empty on load.

_now = datetime.now(timezone.utc)

reports: list[dict] = [
    # ── PERLIS ──
    {
        "id": "ps01",
        "user_lat": 6.4414,
        "user_long": 100.1986,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=PS01",
        "timestamp": (_now - timedelta(hours=8)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "JKR Perlis",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "ps02",
        "user_lat": 6.4550,
        "user_long": 100.2120,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=PS02",
        "timestamp": (_now - timedelta(days=4)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "JKR Perlis",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "ps03",
        "user_lat": 6.4630,
        "user_long": 100.1850,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=PS03",
        "timestamp": (_now - timedelta(days=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "JKR Perlis",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    # ── KEDAH ──
    {
        "id": "kd01",
        "user_lat": 6.1210,
        "user_long": 100.3685,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=KD01",
        "timestamp": (_now - timedelta(hours=3)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBAS Alor Setar",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "kd02",
        "user_lat": 6.1140,
        "user_long": 100.3540,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=KD02",
        "timestamp": (_now - timedelta(days=1)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MBAS Alor Setar",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "kd03",
        "user_lat": 5.9555,
        "user_long": 100.5050,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=KD03",
        "timestamp": (_now - timedelta(days=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPK Sungai Petani",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "kd04",
        "user_lat": 6.3287,
        "user_long": 99.8440,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=KD04",
        "timestamp": (_now - timedelta(hours=10)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPLK Langkawi",
        "estimated_duration": "3 days",
        "status": "Analyzed",
    },
    # ── PENANG ──
    {
        "id": "pg01",
        "user_lat": 5.4141,
        "user_long": 100.3288,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=PG01",
        "timestamp": (_now - timedelta(hours=4)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBPP George Town",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "pg02",
        "user_lat": 5.3553,
        "user_long": 100.3088,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=PG02",
        "timestamp": (_now - timedelta(days=1)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MBPP George Town",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    {
        "id": "pg03",
        "user_lat": 5.2835,
        "user_long": 100.4587,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=PG03",
        "timestamp": (_now - timedelta(days=3)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPSP Seberang Perai",
        "estimated_duration": "4 hours",
        "status": "In Progress",
    },
    {
        "id": "pg04",
        "user_lat": 5.3980,
        "user_long": 100.3050,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=PG04",
        "timestamp": (_now - timedelta(hours=18)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MBPP George Town",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    # ── PERAK ──
    {
        "id": "pk01",
        "user_lat": 4.5975,
        "user_long": 101.0901,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=PK01",
        "timestamp": (_now - timedelta(hours=5)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBI Ipoh",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "pk02",
        "user_lat": 4.5840,
        "user_long": 101.0720,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=PK02",
        "timestamp": (_now - timedelta(days=7)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MBI Ipoh",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "pk03",
        "user_lat": 4.2050,
        "user_long": 100.5920,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=PK03",
        "timestamp": (_now - timedelta(days=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPT Teluk Intan",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    # ── KELANTAN ──
    {
        "id": "kt01",
        "user_lat": 6.1254,
        "user_long": 102.2381,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=KT01",
        "timestamp": (_now - timedelta(hours=7)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPKB Kota Bharu",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "kt02",
        "user_lat": 6.1330,
        "user_long": 102.2510,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=KT02",
        "timestamp": (_now - timedelta(days=5)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPKB Kota Bharu",
        "estimated_duration": "4 hours",
        "status": "In Progress",
    },
    # ── TERENGGANU ──
    {
        "id": "tg01",
        "user_lat": 5.3117,
        "user_long": 103.1324,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=TG01",
        "timestamp": (_now - timedelta(days=1, hours=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MBKT Kuala Terengganu",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    {
        "id": "tg02",
        "user_lat": 5.3020,
        "user_long": 103.1190,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=TG02",
        "timestamp": (_now - timedelta(hours=11)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBKT Kuala Terengganu",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    # ── PAHANG ──
    {
        "id": "ph01",
        "user_lat": 3.8077,
        "user_long": 103.3260,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=PH01",
        "timestamp": (_now - timedelta(hours=9)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPK Kuantan",
        "estimated_duration": "3 days",
        "status": "In Progress",
    },
    {
        "id": "ph02",
        "user_lat": 3.8140,
        "user_long": 103.3400,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=PH02",
        "timestamp": (_now - timedelta(days=8)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPK Kuantan",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "ph03",
        "user_lat": 3.4654,
        "user_long": 101.9770,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=PH03",
        "timestamp": (_now - timedelta(days=3)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPT Temerloh",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    # ── SELANGOR ──
    {
        "id": "sl01",
        "user_lat": 3.0738,
        "user_long": 101.5183,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SL01",
        "timestamp": (_now - timedelta(hours=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBPJ Petaling Jaya",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "sl02",
        "user_lat": 3.1579,
        "user_long": 101.7116,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SL02",
        "timestamp": (_now - timedelta(days=1, hours=3)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPA Ampang Jaya",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "sl03",
        "user_lat": 3.0319,
        "user_long": 101.4455,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=SL03",
        "timestamp": (_now - timedelta(days=10)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MBSA Shah Alam",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "sl04",
        "user_lat": 2.9903,
        "user_long": 101.6538,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SL04",
        "timestamp": (_now - timedelta(hours=14)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPS Subang Jaya",
        "estimated_duration": "3 days",
        "status": "Analyzed",
    },
    {
        "id": "sl05",
        "user_lat": 3.2490,
        "user_long": 101.7373,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SL05",
        "timestamp": (_now - timedelta(days=2, hours=8)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPS Selayang",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    # ── KUALA LUMPUR ──
    {
        "id": "kl01",
        "user_lat": 3.1390,
        "user_long": 101.6869,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=KL01",
        "timestamp": (_now - timedelta(hours=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "kl02",
        "user_lat": 3.1570,
        "user_long": 101.7116,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=KL02",
        "timestamp": (_now - timedelta(days=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    {
        "id": "kl03",
        "user_lat": 3.1200,
        "user_long": 101.6530,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=KL03",
        "timestamp": (_now - timedelta(days=5)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "kl04",
        "user_lat": 3.1710,
        "user_long": 101.6943,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=KL04",
        "timestamp": (_now - timedelta(hours=1)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "3 days",
        "status": "In Progress",
    },
    {
        "id": "kl05",
        "user_lat": 3.1060,
        "user_long": 101.6710,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=KL05",
        "timestamp": (_now - timedelta(days=4)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    # ── PUTRAJAYA ──
    {
        "id": "pj01",
        "user_lat": 2.9264,
        "user_long": 101.6964,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=PJ01",
        "timestamp": (_now - timedelta(days=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "PPj Putrajaya",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    # ── NEGERI SEMBILAN ──
    {
        "id": "ns01",
        "user_lat": 2.7297,
        "user_long": 101.9381,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=NS01",
        "timestamp": (_now - timedelta(hours=12)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBS Seremban",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "ns02",
        "user_lat": 2.5187,
        "user_long": 101.8500,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=NS02",
        "timestamp": (_now - timedelta(days=3, hours=5)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPNP Port Dickson",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
    # ── MELAKA ──
    {
        "id": "mk01",
        "user_lat": 2.1896,
        "user_long": 102.2501,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=MK01",
        "timestamp": (_now - timedelta(hours=15)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBMB Melaka",
        "estimated_duration": "3 days",
        "status": "In Progress",
    },
    {
        "id": "mk02",
        "user_lat": 2.2010,
        "user_long": 102.2400,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=MK02",
        "timestamp": (_now - timedelta(days=9)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MBMB Melaka",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "mk03",
        "user_lat": 2.3120,
        "user_long": 102.3210,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=MK03",
        "timestamp": (_now - timedelta(days=2, hours=10)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPJ Jasin",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    # ── JOHOR ──
    {
        "id": "jh01",
        "user_lat": 1.4927,
        "user_long": 103.7414,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=JH01",
        "timestamp": (_now - timedelta(hours=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBJB Johor Bahru",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "jh02",
        "user_lat": 1.4800,
        "user_long": 103.7600,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=JH02",
        "timestamp": (_now - timedelta(days=1, hours=12)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MBJB Johor Bahru",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "jh03",
        "user_lat": 1.8547,
        "user_long": 102.9325,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=JH03",
        "timestamp": (_now - timedelta(days=4)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPBP Batu Pahat",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "jh04",
        "user_lat": 1.7380,
        "user_long": 103.8970,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=JH04",
        "timestamp": (_now - timedelta(hours=20)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPC Pasir Gudang",
        "estimated_duration": "3 days",
        "status": "Analyzed",
    },
    # ── SABAH ──
    {
        "id": "sb01",
        "user_lat": 5.9804,
        "user_long": 116.0735,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SB01",
        "timestamp": (_now - timedelta(hours=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "DBKK Kota Kinabalu",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "sb02",
        "user_lat": 5.9750,
        "user_long": 116.0550,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SB02",
        "timestamp": (_now - timedelta(days=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "DBKK Kota Kinabalu",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "sb03",
        "user_lat": 5.8390,
        "user_long": 118.1170,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=SB03",
        "timestamp": (_now - timedelta(days=7)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPS Sandakan",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "sb04",
        "user_lat": 5.3117,
        "user_long": 115.2470,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SB04",
        "timestamp": (_now - timedelta(days=1, hours=8)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPL Labuan",
        "estimated_duration": "1 day",
        "status": "Reported",
    },
    {
        "id": "sb05",
        "user_lat": 4.3104,
        "user_long": 117.5965,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SB05",
        "timestamp": (_now - timedelta(hours=16)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPT Tawau",
        "estimated_duration": "3 days",
        "status": "Analyzed",
    },
    # ── SARAWAK ──
    {
        "id": "sw01",
        "user_lat": 1.5497,
        "user_long": 110.3414,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SW01",
        "timestamp": (_now - timedelta(hours=5)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "DBKU Kuching",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "sw02",
        "user_lat": 1.5370,
        "user_long": 110.3530,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=SW02",
        "timestamp": (_now - timedelta(days=11)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "DBKU Kuching",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "sw03",
        "user_lat": 2.3000,
        "user_long": 111.8500,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SW03",
        "timestamp": (_now - timedelta(days=2)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPS Sibu",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "sw04",
        "user_lat": 2.2860,
        "user_long": 111.8280,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SW04",
        "timestamp": (_now - timedelta(hours=22)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MPS Sibu",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "sw05",
        "user_lat": 4.5500,
        "user_long": 114.0200,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=SW05",
        "timestamp": (_now - timedelta(days=6)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "MPM Miri",
        "estimated_duration": "4 hours",
        "status": "Analyzed",
    },
    # ── EXTRA KL METRO CLUSTER (realistic density) ──
    {
        "id": "kl06",
        "user_lat": 3.1480,
        "user_long": 101.7100,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=KL06",
        "timestamp": (_now - timedelta(hours=3)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "1 day",
        "status": "In Progress",
    },
    {
        "id": "kl07",
        "user_lat": 3.1320,
        "user_long": 101.6780,
        "image_file": "https://dummyimage.com/600x400/228b22/fff&text=KL07",
        "timestamp": (_now - timedelta(days=12)).isoformat(),
        "is_pothole": True,
        "size_category": "Small",
        "priority_color": "Green",
        "jurisdiction": "DBKL Kuala Lumpur",
        "estimated_duration": "4 hours",
        "status": "Finished",
    },
    {
        "id": "sl06",
        "user_lat": 3.1120,
        "user_long": 101.6350,
        "image_file": "https://dummyimage.com/600x400/8b0000/fff&text=SL06",
        "timestamp": (_now - timedelta(hours=8)).isoformat(),
        "is_pothole": True,
        "size_category": "Large",
        "priority_color": "Red",
        "jurisdiction": "MBPJ Petaling Jaya",
        "estimated_duration": "3 days",
        "status": "Reported",
    },
    {
        "id": "sl07",
        "user_lat": 3.0530,
        "user_long": 101.6740,
        "image_file": "https://dummyimage.com/600x400/b8860b/fff&text=SL07",
        "timestamp": (_now - timedelta(days=1, hours=16)).isoformat(),
        "is_pothole": True,
        "size_category": "Medium",
        "priority_color": "Yellow",
        "jurisdiction": "MPS Subang Jaya",
        "estimated_duration": "1 day",
        "status": "Analyzed",
    },
]
