import 'dart:math';
import 'package:flutter/material.dart';
import '../models/pothole_report.dart';

class ReportProvider extends ChangeNotifier {
  final List<PotholeReport> _reports = [
    // ────────────────────────────────────────────────────────────────────────
    // NORTHERN MALAYSIA
    // ── PERLIS ──────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'n01',
      userLat: 6.4414,
      userLong: 100.1986,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=N01',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Perlis',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'n02',
      userLat: 6.4550,
      userLong: 100.2120,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=N02',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MDKP Kangar',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'n03',
      userLat: 6.4280,
      userLong: 100.1850,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=N03',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Perlis',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    // ── KEDAH: Jalan Sultanah (town centre) ─────────────────────────────────
    PotholeReport(
      id: 'p1',
      userLat: 6.1205,
      userLong: 100.3685,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P1+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'p2',
      userLat: 6.1230,
      userLong: 100.3710,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P2+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'p3',
      userLat: 6.1188,
      userLong: 100.3660,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P3+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '4 hours',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'p4',
      userLat: 6.1255,
      userLong: 100.3730,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P4+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '2 days',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'p5',
      userLat: 6.1172,
      userLong: 100.3648,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P5+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(hours: 12)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    // ── Cluster B: Lebuhraya Utara-Selatan corridor ───────────────────────
    PotholeReport(
      id: 'p6',
      userLat: 6.0950,
      userLong: 100.3520,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P6+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '3 days',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'p7',
      userLat: 6.0870,
      userLong: 100.3480,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P7+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'p8',
      userLat: 6.0790,
      userLong: 100.3440,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P8+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(hours: 18)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'p9',
      userLat: 6.0710,
      userLong: 100.3395,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P9+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(minutes: 90)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '2 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'p10',
      userLat: 6.0640,
      userLong: 100.3360,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P10+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    // ── Cluster C: Jalan Langgar / Mergong ───────────────────────────────
    PotholeReport(
      id: 'p11',
      userLat: 6.1380,
      userLong: 100.3820,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P11+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(hours: 7)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'p12',
      userLat: 6.1420,
      userLong: 100.3860,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P12+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'p13',
      userLat: 6.1460,
      userLong: 100.3900,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P13+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '4 hours',
      status: 'In Progress',
    ),
    // ── Cluster D: Jalan Stadium / Taman Indera Kayangan ──────────────────
    PotholeReport(
      id: 'p14',
      userLat: 6.1150,
      userLong: 100.3900,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P14+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 36)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'p15',
      userLat: 6.1100,
      userLong: 100.3940,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P15+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '1 day',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'p16',
      userLat: 6.1060,
      userLong: 100.3970,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P16+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(hours: 48)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '4 hours',
      status: 'Analyzed',
    ),
    // ── Cluster E: Jalan Kuala Kedah ──────────────────────────────────────
    PotholeReport(
      id: 'p17',
      userLat: 6.1020,
      userLong: 100.4100,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P17+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'p18',
      userLat: 6.0980,
      userLong: 100.4150,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P18+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '1 day',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'p19',
      userLat: 6.0930,
      userLong: 100.4200,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P19+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 22)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    // ── Cluster F: Jalan Teluk Wanjah / Airport road ──────────────────────
    PotholeReport(
      id: 'p20',
      userLat: 6.1600,
      userLong: 100.4050,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P20+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(hours: 10)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '4 hours',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'p21',
      userLat: 6.1650,
      userLong: 100.4120,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P21+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPPB Alor Setar',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'p22',
      userLat: 6.1700,
      userLong: 100.4180,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P22+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Kedah',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    // ── Cluster G: Kepala Batas / Kubang Pasu outskirts ───────────────────
    PotholeReport(
      id: 'p23',
      userLat: 6.2000,
      userLong: 100.4350,
      imageFile:
          'https://dummyimage.com/600x400/006400/fff&text=P23+Small+Green',
      timestamp: DateTime.now().subtract(const Duration(days: 9)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'p24',
      userLat: 6.2080,
      userLong: 100.4420,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=P24+Large+Red',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '2 days',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'p25',
      userLat: 6.2150,
      userLong: 100.4500,
      imageFile:
          'https://dummyimage.com/600x400/b8860b/fff&text=P25+Medium+Yellow',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 8)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'Majlis Daerah Kubang Pasu',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    // ────────────────────────────────────────────────────────────────────────
    // ── PENANG ───────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'pg01',
      userLat: 5.4141,
      userLong: 100.3288,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PG01',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBPP George Town',
      estimatedDuration: '2 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'pg02',
      userLat: 5.4200,
      userLong: 100.3350,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PG02',
      timestamp: DateTime.now().subtract(const Duration(hours: 9)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBPP George Town',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'pg03',
      userLat: 5.3990,
      userLong: 100.3660,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PG03',
      timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBSP Seberang Perai',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'pg04',
      userLat: 5.3860,
      userLong: 100.3720,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=PG04',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MBSP Seberang Perai',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'pg05',
      userLat: 5.4080,
      userLong: 100.3150,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PG05',
      timestamp: DateTime.now().subtract(const Duration(hours: 30)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Pulau Pinang',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    // ── PERAK ────────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'pk01',
      userLat: 4.5975,
      userLong: 101.0901,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PK01',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBIP Ipoh',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'pk02',
      userLat: 4.6050,
      userLong: 101.0820,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PK02',
      timestamp: DateTime.now().subtract(const Duration(hours: 14)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBIP Ipoh',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'pk03',
      userLat: 4.5880,
      userLong: 101.1000,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PK03',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Perak',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'pk04',
      userLat: 4.8503,
      userLong: 100.7329,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=PK04',
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MDTB Taiping',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'pk05',
      userLat: 4.8400,
      userLong: 100.7450,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PK05',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MDTB Taiping',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    // ────────────────────────────────────────────────────────────────────────
    // CENTRAL MALAYSIA
    // ── SELANGOR ─────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'sg01',
      userLat: 3.0738,
      userLong: 101.5183,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SG01',
      timestamp: DateTime.now().subtract(const Duration(minutes: 20)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBSA Shah Alam',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sg02',
      userLat: 3.0820,
      userLong: 101.5100,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SG02',
      timestamp: DateTime.now().subtract(const Duration(hours: 7)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBSA Shah Alam',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'sg03',
      userLat: 3.1073,
      userLong: 101.6067,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SG03',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBPJ Petaling Jaya',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'sg04',
      userLat: 3.1150,
      userLong: 101.6150,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=SG04',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MBPJ Petaling Jaya',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'sg05',
      userLat: 3.0560,
      userLong: 101.5851,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SG05',
      timestamp: DateTime.now().subtract(const Duration(hours: 11)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPAJ Subang Jaya',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sg06',
      userLat: 3.0449,
      userLong: 101.4456,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SG06',
      timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 30)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPKlang',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sg07',
      userLat: 3.0510,
      userLong: 101.4380,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=SG07',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MPKlang',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'sg08',
      userLat: 3.0900,
      userLong: 101.5600,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SG08',
      timestamp: DateTime.now().subtract(const Duration(hours: 40)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Selangor',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    // ── KUALA LUMPUR (W.P.) ──────────────────────────────────────────────────
    PotholeReport(
      id: 'kl01',
      userLat: 3.1390,
      userLong: 101.6869,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=KL01',
      timestamp: DateTime.now().subtract(const Duration(minutes: 10)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'DBKL',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'kl02',
      userLat: 3.1578,
      userLong: 101.7123,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=KL02',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'DBKL',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'kl03',
      userLat: 3.1480,
      userLong: 101.6980,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=KL03',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'DBKL',
      estimatedDuration: '2 days',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'kl04',
      userLat: 3.1280,
      userLong: 101.6720,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=KL04',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR WP',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'kl05',
      userLat: 3.1700,
      userLong: 101.7050,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=KL05',
      timestamp: DateTime.now().subtract(const Duration(hours: 16)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'DBKL',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'kl06',
      userLat: 3.1200,
      userLong: 101.6600,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=KL06',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'DBKL',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    // ── PUTRAJAYA (W.P.) ─────────────────────────────────────────────────────
    PotholeReport(
      id: 'pj01',
      userLat: 2.9264,
      userLong: 101.6964,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=PJ01',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'PPj Putrajaya',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'pj02',
      userLat: 2.9350,
      userLong: 101.7050,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PJ02',
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'PPj Putrajaya',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    // ── NEGERI SEMBILAN ───────────────────────────────────────────────────────
    PotholeReport(
      id: 'ns01',
      userLat: 2.7297,
      userLong: 101.9381,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=NS01',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPNS Seremban',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'ns02',
      userLat: 2.7180,
      userLong: 101.9480,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=NS02',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPNS Seremban',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'ns03',
      userLat: 2.8097,
      userLong: 101.7972,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=NS03',
      timestamp: DateTime.now().subtract(const Duration(days: 8)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Negeri Sembilan',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'ns04',
      userLat: 2.8200,
      userLong: 101.8100,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=NS04',
      timestamp: DateTime.now().subtract(const Duration(hours: 20)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPNS Nilai',
      estimatedDuration: '3 days',
      status: 'Analyzed',
    ),
    // ── MELAKA ───────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'ml01',
      userLat: 2.1896,
      userLong: 102.2501,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=ML01',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBMB Melaka',
      estimatedDuration: '2 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'ml02',
      userLat: 2.2020,
      userLong: 102.2620,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=ML02',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBMB Melaka',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'ml03',
      userLat: 2.1760,
      userLong: 102.2400,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=ML03',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Melaka',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'ml04',
      userLat: 2.2300,
      userLong: 102.2800,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=ML04',
      timestamp: DateTime.now().subtract(const Duration(hours: 13)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBMB Melaka',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    // ────────────────────────────────────────────────────────────────────────
    // SOUTHERN MALAYSIA
    // ── JOHOR ────────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'jh01',
      userLat: 1.4927,
      userLong: 103.7414,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=JH01',
      timestamp: DateTime.now().subtract(const Duration(minutes: 35)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBJB Johor Bahru',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'jh02',
      userLat: 1.5000,
      userLong: 103.7550,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=JH02',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBJB Johor Bahru',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'jh03',
      userLat: 1.4800,
      userLong: 103.7300,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=JH03',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBJB Johor Bahru',
      estimatedDuration: '2 days',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'jh04',
      userLat: 1.5338,
      userLong: 103.6607,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=JH04',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MPJBT Skudai',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'jh05',
      userLat: 1.8610,
      userLong: 103.0530,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=JH05',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'JKR Johor',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'jh06',
      userLat: 2.0260,
      userLong: 102.9280,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=JH06',
      timestamp: DateTime.now().subtract(const Duration(hours: 23)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Johor',
      estimatedDuration: '3 days',
      status: 'In Progress',
    ),
    // ────────────────────────────────────────────────────────────────────────
    // EAST COAST PENINSULAR MALAYSIA
    // ── PAHANG ───────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'ph01',
      userLat: 3.8077,
      userLong: 103.3260,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PH01',
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPKB Kuantan',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'ph02',
      userLat: 3.8200,
      userLong: 103.3400,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=PH02',
      timestamp: DateTime.now().subtract(const Duration(hours: 19)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPKB Kuantan',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'ph03',
      userLat: 3.5250,
      userLong: 101.9050,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=PH03',
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'MDBP Bentong',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'ph04',
      userLat: 3.7900,
      userLong: 103.3100,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=PH04',
      timestamp: DateTime.now().subtract(const Duration(hours: 11)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Pahang',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    // ── TERENGGANU ────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'tr01',
      userLat: 5.3296,
      userLong: 103.1370,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=TR01',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBKT Kuala Terengganu',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'tr02',
      userLat: 5.3400,
      userLong: 103.1500,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=TR02',
      timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBKT Kuala Terengganu',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'tr03',
      userLat: 5.3100,
      userLong: 103.1200,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=TR03',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Terengganu',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'tr04',
      userLat: 4.2350,
      userLong: 103.4200,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=TR04',
      timestamp: DateTime.now().subtract(const Duration(hours: 27)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Terengganu',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    // ── KELANTAN ──────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'kn01',
      userLat: 6.1254,
      userLong: 102.2381,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=KN01',
      timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 15)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPKB Kota Bharu',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'kn02',
      userLat: 6.1350,
      userLong: 102.2500,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=KN02',
      timestamp: DateTime.now().subtract(const Duration(hours: 15)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPKB Kota Bharu',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'kn03',
      userLat: 6.1100,
      userLong: 102.2200,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=KN03',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Kelantan',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'kn04',
      userLat: 5.7840,
      userLong: 102.0150,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=KN04',
      timestamp: DateTime.now().subtract(const Duration(hours: 10)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Kelantan',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    // ────────────────────────────────────────────────────────────────────────
    // EAST MALAYSIA
    // ── SARAWAK ───────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'sw01',
      userLat: 1.5533,
      userLong: 110.3592,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SW01',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBKS Kuching',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sw02',
      userLat: 1.5650,
      userLong: 110.3700,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SW02',
      timestamp: DateTime.now().subtract(const Duration(hours: 12)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MBKS Kuching',
      estimatedDuration: '1 day',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'sw03',
      userLat: 1.5400,
      userLong: 110.3450,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=SW03',
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Sarawak',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'sw04',
      userLat: 2.3352,
      userLong: 111.8299,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SW04',
      timestamp: DateTime.now().subtract(const Duration(hours: 7)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPSR Sibu',
      estimatedDuration: '2 days',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'sw05',
      userLat: 3.3185,
      userLong: 113.0419,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SW05',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPUB Bintulu',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sw06',
      userLat: 4.3995,
      userLong: 113.9914,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SW06',
      timestamp: DateTime.now().subtract(const Duration(hours: 18)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MBMIRI Miri',
      estimatedDuration: '3 days',
      status: 'In Progress',
    ),
    // ── SABAH ────────────────────────────────────────────────────────────────
    PotholeReport(
      id: 'sb01',
      userLat: 5.9804,
      userLong: 116.0735,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SB01',
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'DBKK Kota Kinabalu',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'sb02',
      userLat: 5.9920,
      userLong: 116.0850,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SB02',
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'DBKK Kota Kinabalu',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'sb03',
      userLat: 5.9680,
      userLong: 116.0600,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=SB03',
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'JKR Sabah',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
    PotholeReport(
      id: 'sb04',
      userLat: 5.8457,
      userLong: 118.1181,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SB04',
      timestamp: DateTime.now().subtract(const Duration(hours: 9)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'MPSDS Sandakan',
      estimatedDuration: '2 days',
      status: 'In Progress',
    ),
    PotholeReport(
      id: 'sb05',
      userLat: 4.2421,
      userLong: 117.8872,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=SB05',
      timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 7)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'MPTAWAU Tawau',
      estimatedDuration: '1 day',
      status: 'Analyzed',
    ),
    PotholeReport(
      id: 'sb06',
      userLat: 5.3247,
      userLong: 115.2339,
      imageFile: 'https://dummyimage.com/600x400/8b0000/fff&text=SB06',
      timestamp: DateTime.now().subtract(const Duration(hours: 32)),
      isPothole: true,
      sizeCategory: 'Large',
      priorityColor: 'Red',
      jurisdiction: 'JKR Sabah',
      estimatedDuration: '3 days',
      status: 'Reported',
    ),
    // ── LABUAN (W.P.) ────────────────────────────────────────────────────────
    PotholeReport(
      id: 'lb01',
      userLat: 5.2831,
      userLong: 115.2308,
      imageFile: 'https://dummyimage.com/600x400/b8860b/fff&text=LB01',
      timestamp: DateTime.now().subtract(const Duration(hours: 14)),
      isPothole: true,
      sizeCategory: 'Medium',
      priorityColor: 'Yellow',
      jurisdiction: 'PLBLabuan',
      estimatedDuration: '1 day',
      status: 'Reported',
    ),
    PotholeReport(
      id: 'lb02',
      userLat: 5.2950,
      userLong: 115.2420,
      imageFile: 'https://dummyimage.com/600x400/006400/fff&text=LB02',
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      isPothole: true,
      sizeCategory: 'Small',
      priorityColor: 'Green',
      jurisdiction: 'PLBLabuan',
      estimatedDuration: '4 hours',
      status: 'Finished',
    ),
  ];

  List<PotholeReport> get reports => _reports;

  Future<void> submitReport(double lat, double long, String imagePath) async {
    // Simulate 3-second network delay for Gemini AI analysis
    await Future.delayed(const Duration(seconds: 3));

    final random = Random();
    final sizes = ['Small', 'Medium', 'Large'];
    final size = sizes[random.nextInt(sizes.length)];

    String priority;
    String duration;
    if (size == 'Large') {
      priority = 'Red';
      duration = '3 days';
    } else if (size == 'Medium') {
      priority = 'Yellow';
      duration = '1 day';
    } else {
      priority = 'Green';
      duration = '4 hours';
    }

    final newReport = PotholeReport(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userLat: lat,
      userLong: long,
      imageFile: imagePath,
      timestamp: DateTime.now(),
      isPothole: true,
      sizeCategory: size,
      priorityColor: priority,
      jurisdiction: random.nextBool()
          ? 'JKR Kedah'
          : 'Majlis Daerah Padang Terap',
      estimatedDuration: duration,
      status: 'Analyzed',
    );

    _reports.add(newReport);
    notifyListeners();
  }

  void updateStatus(String id, String newStatus) {
    final index = _reports.indexWhere((report) => report.id == id);
    if (index != -1) {
      _reports[index] = _reports[index].copyWith(status: newStatus);
      notifyListeners();
    }
  }
}
